---
title: "Max Sandbox"
author: "Max"
date: "January 31, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(usdm) #for multicollinearity
library(tidyverse)
library(ggplot2)

```

# Loading Data

```{r load}
feat  = read.csv('../Data/features.csv')
labels = read.csv('../Data/labels.csv')
predictors = names(dplyr::select(feat,-JobName))
target = 'y3'
data = inner_join(feat,select_at(labels,c('JobName',target)),by='JobName')
```

# Data validation


```{r data}

data.cc  = complete.cases(data)
data.notComplete = data[! data.cc,]
data.complete = data[data.cc,]
message('Non-Complete cases: ',nrow(data.notComplete))
```

**Question**: Y3 has all  the non-complete casesI guess hese are the cases for prediction, right?

No null-cases on features :)

```{r feat}
feat.cc  = complete.cases(feat)
feat.notComplete = feat[! feat.cc,]
feat.complete = feat[feat.cc,]
message('Non-Complete cases: ',nrow(feat.notComplete))
```

# Distribution

## Target Variable

```{r}
ggplot(gather(select_at(data,target)), aes(value)) + 
  geom_histogram(aes(y=..density..),bins = 50,fill='light blue') + 
  geom_density() + 
  facet_wrap(~key, scales = 'free',ncol=4)

```


## Predictors

```{r  fig.height=70, fig.width=7}
ggplot(gather(select_at(data,predictors)), aes(value)) + 
  geom_histogram(aes(y=..density..),bins = 50,fill='light blue') + 
  geom_density() + 
  facet_wrap(~key, scales = 'free',ncol=4)
```

# Multicollinearity - VIF

No Multicollinearity among predictors

```{r vif}
vifDF = usdm::vif(select_at(data,predictors)) %>%
  arrange(desc(VIF))
head(vifDF,10)
```

 
